locallibrary/catalog/urls.py
# urls de nuestra aplicación catalogo
from django.urls import path
from .views import index, acerca_de, BookListView, BookDetailView, AuthorListView, \
                    AuthorDetailView, SearchResultsListView, LibrosPrestados, renovar_libro, \
                    AuthorCreate, AuthorUpdate, AuthorDelete


urlpatterns = [
    path('', index, name='index'),
    path('acerca-de/', acerca_de, name='acercade'),
    path('libros/', BookListView.as_view(), name='lista-libros'),
    path('libros/<int:pk>', BookDetailView.as_view(), name='detalle-libro'),
    path('autores/', AuthorListView.as_view(), name='lista-autores'),
    path('autores/<int:pk>', AuthorDetailView.as_view(), name='detalle-autor'),
    path('buscador/', SearchResultsListView.as_view(), name='buscar'),
    path('prestados/', LibrosPrestados.as_view(), name='prestados'),
    path('libro/<uuid:pk>/renovar/', renovar_libro, name='renovar-fecha'),
    path('autores/create/', AuthorCreate.as_view(), name='author-create'),
    path('autores/<int:pk>/update/', AuthorUpdate.as_view(), name='author-update'),
    path('autores/<int:pk>/delete/', AuthorDelete.as_view(), name='author-delete'),



]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include

# importamos la vista de nuestra app catalog
from catalog.views import index_general

urlpatterns = [
    path('admin/', admin.site.urls),
    # castellanizar url catálogo
    path('catalogo/', include('catalog.urls')), 
    ## para el index general
    path('', index_general, name='index_general'),
    # para el debug_toolbar
    path('__debug__/', include('debug_toolbar.urls')),
]

locallibrary/catalog/models.py
from django.db import models
import uuid

# https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Models
# Create your models here.

class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', 
        on_delete=models.SET_NULL, # que pasa si borramos el autor?
        null=True)  # puede ser nulo?
    summary = models.TextField(
        max_length=1000, 
        help_text='Enter a brief description of the book',
        blank=True)
    isbn = models.CharField(
        'ISBN', 
        max_length=13, 
        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    genre = models.ManyToManyField('Genre', 
        help_text='Select a genre for this book')

    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        """String for representing the Model object.""" 
        return self.title
    # display genre paara el admin
    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'


class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=180, 
        help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name

class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200, 
        help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        """String for representing the Model object."""
        return self.name

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, 
        default=uuid.uuid4, 
        help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', 
        on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200, blank=True)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} - {self.book.title}'

locallibrary/catalog/forms.py
# archivo forms.py
from django import forms
import datetime 
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.forms import ModelForm
from catalog.models import BookInstance


class RenewBookForm(forms.Form):
    due_back = forms.DateField(help_text="Introduce una fecha entre hoy y 4 semanas(default 3).")

    def clean_due_back(self):

        data = self.cleaned_data['due_back']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

### Ahora el mismo formulario pero usando ModelForm
class RenewBookModelForm(ModelForm):
    def clean_due_back(self):
       data = self.cleaned_data['due_back']

       # Check if a date is not in the past.
       if data < datetime.date.today():
           raise ValidationError(_('Invalid date - renewal in past'))

       # Check if a date is in the allowed range (+4 weeks from today).
       if data > datetime.date.today() + datetime.timedelta(weeks=4):
           raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

       # Remember to always return the cleaned data.
       return data

    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('Renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}


class ContactForm(forms.Form):
    ''' Contact form '''
    #campos del formulario
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)
    #tuning del formulario
    from_email.widget.attrs.update({'class': 'form-control'})
    subject.widget.attrs.update({'class': 'form-control'})
    message.widget.attrs.update({'class': 'form-control'})

locallibrary/catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from catalog.models import Book, BookInstance, Author
from django.views import generic
from django.views.generic import ListView, DetailView
import datetime
from catalog.forms import RenewBookForm, RenewBookModelForm
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from catalog.forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages
from django.utils.translation import gettext_lazy as _



# Create your views here.
def index_general(request):
    
    return render(request, 'index-general.html')

def acerca_de(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['admin@example.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            messages.success(request, _('Message sent successfully!'))
            return HttpResponseRedirect(reverse('index'))
        messages.error(request, _("Error. Message not sent."))

    context = {}
    context['title'] = 'Acerca de'
    context['coords'] = '41.656771,-0.8960287'  # "41.6447242,-0.9231553"
    context['form'] = ContactForm()

    return render(request, 'catalog/acerca_de.html', context)

def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1
    ultimos = Book.objects.all().order_by('-id')[:10]

    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={
            'num_books':num_books,
            'num_instances':num_instances,
            'num_instances_available':num_instances_available,
            'num_authors':num_authors,
            'num_visits':num_visits,
            'ultimos':ultimos},
    )


## Listas Genéricas
class BookListView(ListView):
    '''Vista generica para el listado de libros'''
    model = Book
    paginate_by = 15
    def get_queryset(self):
        return Book.objects.all().order_by('title')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(BookListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['ahora'] = datetime.datetime.now()
        return context

class BookDetailView(DetailView):
    '''Vista generica para el detalle de un libro'''
    model = Book

class AuthorListView(ListView):
    '''Vista generica para el listado de autores'''
    model = Author
    paginate_by = 15

class AuthorDetailView(DetailView):
    '''Vista generica para el detalle de un autor'''
    model = Author

## Buscador
class SearchResultsListView(ListView):
    model = Book
    def get_queryset(self): # new
        query = self.request.GET.get('q')
        # voy a guardar query para el contexto
        if query:
            self.query = query
            return Book.objects.filter(title__icontains=query)
        else:
            return []

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(SearchResultsListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['busqueda'] = self.query
        context['anterior'] = self.request.META.get('HTTP_REFERER')
        return context

class LibrosPrestados(ListView):
    model = BookInstance
    template_name = 'catalog/libros_prestados.html'
    paginate_by = 15

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('-due_back')



# vista para renovar un libro
def renovar_libro(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
        # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookModelForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['due_back']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('prestados') )

    # If this is a GET (or any other method) create the default form.
    else:
        #inicializa la fecha de renovación dentro de 3 semanas
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookModelForm(initial={'due_back': proposed_renewal_date})

    context = { 
        'form': form, 
        'book_instance': book_instance, 
    }
    return render(request, 'catalog/renovacion_fecha.html', context)

## Gestióm de autores con vistas genéricas
class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    success_url = reverse_lazy('lista-autores')
    #initial = {'date_of_death': '11/06/2020'}

class AuthorUpdate(UpdateView):
    model = Author
    fields = '__all__' # Not recommended (potential security issue if more fields added)
    success_url = reverse_lazy('lista-autores')

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('lista-autores')

locallibrary/catalog/templates/catalog/acerca_de.html
{% extends "base.html" %}


{% block title %} {{ title }}
{% endblock %}

{% block extracss %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
  integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
  crossorigin="" />

<style>
  #map {
    height: 400px;
  }
</style>
{% endblock %}


{% block content %}
<h1 class="my-4 text-center">{{ title }}</h1>
<div class="row">
  <div class="col-md-6">
    <div id="map"></div>
  </div>
  <div class="col-md-6">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="form-actions">
        <button class="btn btn-primary" type="submit">Send</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

{% block extrajs %}

<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
  integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
  crossorigin=""></script>

<script>
  var mimapa = L.map('map').setView([{{ coords }}], 13);

  L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://cloudmade.com">CloudMade</a>',
    maxZoom: 18
  }).addTo(mimapa);

  L.marker([{{ coords }}]).addTo(mimapa).bindPopup("CPI Los Enlaces");
</script>


{% endblock %}

locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
  <p><strong>{% trans "Are you sure you want to delete this author?" %}</strong></p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" value="Si" />
    <a href="{% url 'lista-autores' %}" class="btn btn-primary">No</a>
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base.html" %}
{% load static %}

    {% block title %}Detalle del autor{% endblock %}
        
        {% block content %}
        <h1>Detalle del autor</h1>
        <div class="row">
            <div class="col-8">
                <h2>{{ author }}</h2>
                <p><strong>Nombre:</strong> {{ author.first_name }}</p>
                <p><strong>Apellido:</strong> {{ author.last_name }}</p>
                <p><strong>Fecha de nacimiento:</strong> {{ author.date_of_birth }}</p>
                <p><strong>Fecha de fallecimiento:</strong> {{ author.date_of_death }}</p>
                <strong>Libros:</strong>
                {%for book in author.book_set.all%}
                <p>-<a href="{% url 'detalle-libro' book.id %}">{{ book.title }}</a></p>
                {%endfor%}


            </div>
        </div>
        {% endblock %}

 

locallibrary/catalog/templates/catalog/author_form.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>{% trans "Author" %}</h1>
  <form action="" method="post">
    {% csrf_token %}  <!--Atención!! Protección CSRF-->
    <table class="table table-striped">
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends "base.html" %}
{% load static %}
     
    {% block title %}Listado de autores{% endblock %}
     
    {% block content %}
    <h1>Listado de autores</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Autor</th>
                    <th scope="col">Modificar</th>
                    <th scope="col">Eliminar</th>
                </tr>
            {% for autor in author_list %}
            <tr>
                <td><a href="{% url 'detalle-autor' autor.id %}">{{ autor }}</a></td>
                <td><a href="{% url 'author-update' autor.id %}">&#9999;</a></td>
                <td><a href="{% url 'author-delete' autor.id %}">&#128465;</a></td>
            </tr>
            {% endfor %}
        </table>
    <!--Para que salga debajo de todo para cambiar de página-->
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo;</a>
                <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
             
            <span class="current">
                Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
            </span>
             
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                <a href="?page={{ page_obj.paginator.num_pages }}"> &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% endblock %}
    

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Detalle del libro{% endblock %}

{% block content %}
    <h1>Detalle del libro</h1>
    <div class="row">
        <div class="col-8">
            <h2>{{ book.title }}</h2>
            <p><strong>Autor:</strong> {{ book.author }}</p>
            <p><strong>Resumen:</strong> {{ book.summary }}</p>
            <p><strong>ISBN:</strong> {{ book.isbn }}</p>
            <p><strong>Género:</strong> {{ book.genre.all|join:", " }}</p>
            <p><strong>Ejemplares:</strong> {{ book.bookinstance_set.all.count }}</p>
            <p><strong>Estado ejemplares:</strong>
                {% for instance in book.bookinstance_set.all %}
                    {% if instance.status == 'a' %}
                        <span class="badge bg-success">Disponible</span>
                    {% elif instance.status == 'm' %}
                        <span class="badge bg-warning">Mantenimiento</span>
                    {% elif instance.status == 'r' %}
                        <span class="badge bg-info">Reservado</span>
                    {% else %}
                        <span class="badge bg-danger">Prestado</span>
                    {% endif %}
                {% endfor %}
            </p>
            
        </div>

    </div>


{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Listado de libros{% endblock %}

{% block content %}
<h1>Listado de libros</h1>
<h2>{{ ahora }}</h2>
{% if anterior %}
<a href="{{ anterior }}">Volver</a>
{% endif %}
<ul class="list-group">
    {% for libro in book_list %}

    <li class="list-group-item"><a href="{% url 'detalle-libro' libro.id %}">{{ libro }}</a></li>


    {% empty %} <!--Si no hay libros-->
        <li class="list-group-item">No hay libros que coincida con <strong>{{ query }}</strong></li>

    {% endfor %}

</ul>

<!--Para que salga debajo de todo para cambiar de página-->

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo;</a>
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}

        
        <span class="current">
            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
            <a href="?page={{ page_obj.paginator.num_pages }}"> &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

locallibrary/catalog/templates/catalog/libros_prestados.html
{% extends "base.html" %}
{% load static %}

{% block title %}Libros prestados{% endblock %}
{% block content %}
<h1>Libros prestados</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Libro</th>
            <th scope="col">Fecha de devolución</th>
            <th scope="col">Modificar fecha</th>
        </tr>
    </thead>
    <tbody>
        {% for libro in bookinstance_list %}
        <tr>
            <td>{{ libro.book.title }}</td>
            <td>{{ libro.due_back }}</td>
            <td><a href="{% url 'renovar-fecha' libro.id %}"> Modificar </a></td>
        {% endfor %}
    </tbody>
</table>
<!--Para que salga debajo de todo para cambiar de página-->

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo;</a>
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}

        
        <span class="current">
            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
            <a href="?page={{ page_obj.paginator.num_pages }}"> &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

locallibrary/catalog/templates/catalog/renovacion_fecha.html
{% extends "base.html" %}

{% block content %}
  <h1>Renovar libro para {{ book_instance.book.title }} </h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Renovar" />
  </form>
{% endblock %}